version: "3.9"
    
services:  
  wordpress:    
    image: wordpress:latest
    container_name: wordpress
    env_file:
      - ./environment.env
      
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8000:80"
    restart: always
    
  nginx-proxy:
    image: nginx:latest
    volumes:
      - /srv/nginx-proxy/conf/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    restart: always
    depends_on:
      - wordpress
volumes:  
  wordpress_data: {}