version: "3.3"
services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_container
    environment:  
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      MYSQL_USER: db_name
      MYSQL_PASSWORD: user_name
      MYSQL_DATABASE: user_pass
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - proxy
  
  wordpress:
    depends_on:
      - db
    image: wordpress:php8.1-apache
    container_name: wp_container
    volumes:
      - ./wordpress:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      WORDPRESS_DB_USER: user_name
      WORDPRESS_DB_PASSWORD: user_pass
      WORDPRESS_DB_NAME: db_name
    networks:
      - proxy

  nginx:
    depends_on:
      - wordpress
    image: nginx:1.22
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - proxy

volumes:
  db_data: {}
  nginx: {}

networks:
    proxy: 
      driver: bridge