version: '3.7'

volumes:
  wordpress:
  db:

services:
  proxy:
    image: nginx
    container_name: apiki_challenge_proxy
    restart: unless_stopped
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - wordpress

  wordpress:
    image: wordpress:6.0.3-php8.0-apache
    container_name: apiki_challenge_wordpress
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    depends_on:
      - db
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    container_name: apiki_challenge_db
    restart: unless_stopped
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql