version: "3.9"
services:

    wordpress:
        image: wordpress:php8.1-apache
        container_name: wp-wordpress
        env_file:
            - .env
        restart: unless-stopped
        networks:
            - wordpress
        depends_on:
            - database
        environment:
            - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
            - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
            - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
            - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
        volumes:
            - ./wordpress:/var/www/html

    database:
        # default port 3306
        image: mysql:8
        container_name: wp-database
        env_file:
            - .env
        restart: unless-stopped
        networks:
            - wordpress
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - ${MYSQL_LOCAL_HOME}:/var/lib/mysql
        command:
            - '--default-authentication-plugin=mysql_native_password'


    nginx:
        container_name: nginx
        image: nginx:latest
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        networks:
            - wordpress
        depends_on:
            - wordpress
        volumes:
            - ./nginx_conf:/etc/nginx/conf.d
    
networks:
  wordpress:
    name: wp-wordpress
    driver: bridge