version: '3.1'
services: 
    app: 
      build:
        context: .
        dockerfile: Dockerfile
      container_name: app
      restart: unless-stopped
      working_dir: /var/www
      depends_on:
        - db
      volumes:
        - ./wordpress:/var/www
      tty: true
      environment:
        SERVICE_NAME: app
        SERVICE_TAGS: dev    
      networks:
        - wp-network
    web:
      image: nginx:alpine
      container_name: web
      restart: unless-stopped
      tty: true
      ports:
        - 80:80
        - 443:443
      volumes:
        - ./wordpress:/var/www
        - ./docker/nginx:/etc/nginx/conf.d
      networks:
        - wp-network
    db:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: unless-stopped
      ports:
        - 3306:3306
      environment:
        - MYSQL_DATABASE=wordpress
        - MYSQL_ROOT_PASSWORD=root
      volumes:
        - ./docker/mysql:/var/lib/mysql
      networks:
        - wp-network
networks:
  wp-network:
    driver: bridge