variable "region" {}
variable "environment" {}
variable "service" {}
variable "vpc_cidr" {}
variable "public_subnets" {}
variable "private_subnets" {}
variable "azs" {}
variable "single_natgw" {}
variable "instance_type" {}
variable "clustername" {}
variable "database_name" {}
variable "master_username" {}
variable "zone_domain" {}
variable "zone_id" {}
variable "cluster_identifier" {}
variable "engine" {}
variable "engine_version" {}
variable "engine_mode" {}
variable "desired_ecs" {}
variable "min_ecs" {}
variable "max_ecs" {}
variable "access_key" {}
variable "secret_key" {}
