- name: set_fact | figure out network device of private network
  set_fact:
    private_interface: "{{ hostvars[inventory_hostname]['ansible_' + item]['device'] }}"
  when:
    - hostvars[inventory_hostname]['ansible_' + item].ipv4 is defined
    - hostvars[inventory_hostname]['ansible_' + item]['ipv4']['address'] | ansible.utils.ipaddr("{{ mgmt_net }}")
  with_items: "{{ ansible_interfaces }}"

- name: get master node ip
  set_fact: 
    master_node_ip: "{{ hostvars[inventory_hostname]['ansible_' + private_interface]['ipv4']['address'] }}"
  when:
    - hostvars[inventory_hostname]['ansible_' + private_interface].ipv4 is defined

- name: Init a new swarm with default parameters
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ hostvars[inventory_hostname]['ansible_' + private_interface]['ipv4']['address'] }}"
  register: docker_swarm_state

- name: add dummy host 
  add_host:
    name: "MASTER_NODE"
    ip_addr: "{{ hostvars[inventory_hostname]['ansible_' + private_interface]['ipv4']['address'] }}"
    token: "{{ docker_swarm_state.swarm_facts.JoinTokens.Manager }}"
