---
- name: install prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates 
      - curl 
      - gnupg-agent
      - software-properties-common
      - python3-docker # needed for community.docker 
    update_cache: yes

- name: add apt-key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: add docker repo
  apt_repository:
    repo: deb [[arch=amd64] https://download.docker.com/linux/ubuntu focal stable

- name: install docker 
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - docker-compose
      - containerd.io

# Installs Docker SDK
- name: install python package manager
  apt:
    name: python3-pip

- name: install python sdk
  pip:
    state: present
    name: "{{ packages }}"
  become: yes
  become_user: "{{ user }}"
  vars:
    packages:
      - docker
      - jsondiff
      - pyyaml
      - requests
      - paramiko
      - pyOpenSSL
      - backports.ssl_match_hostname
      # - docker-compose
      # - pywin32

- name: Add user "{{ user }}" to docker group
  user: 
    name: "{{ user }}"
    groups: docker, sudo, adm
    append: yes

- name: Reset ssh connection to allow user changes to affect 'current login user'
  ansible.builtin.meta: reset_connection