---
- name: Cria diretório base para o docker-compose.yml
  file: 
    path: "{{ item }}" 
    state: directory 
    mode: 0755 
    owner: "{{ usuario }}"
    group: "{{ usuario }}"
  loop: "{{ dirs }}"

- name: Copia nginx.conf para o server
  copy: 
    src: nginx.conf 
    dest: "/home/{{ usuario }}/nginx-conf/"
    owner: "{{ usuario }}"
    group: "{{ usuario }}"
    mode: u=rw,g=r,o=r

- name: Copia docker-compose.yml para o diretório do projeto
  template:
    src: docker-compose.j2
    dest: "{{ projeto_dir }}/docker-compose.yml"
    owner: "{{ usuario }}"
    group: "{{ usuario }}"
    mode: 0644
...