---
- name: Cria os diretórios necessários
  file: 
    path: "{{ item }}" 
    state: directory 
    mode: 0755 
    owner: "{{ usuario }}"
    group: "{{ usuario }}"
  loop: "{{ dirs }}"

- name: Copia nginx-http.conf para o server
  copy: 
    src: nginx-http.conf 
    dest: "/home/{{ usuario }}/nginx-conf/nginx.conf"
    owner: "{{ usuario }}"
    group: "{{ usuario }}"
    mode: u=rw,g=r,o=r

- name: Copia docker-compose.yml para o diretório do projeto
  template:
    src: docker-compose.j2
    dest: "{{ projeto_dir }}/docker-compose.yml"
    owner: "{{ usuario }}"
    group: "{{ usuario }}"
    mode: 0644

- name: Executa o docker-compose do Wordpress
  command: docker-compose -f docker-compose.yml up -d
  args:
    chdir: "{{ projeto_dir }}"

- name: Checando se os containers foram iniciados e o {{ domain }} está acessível
  wait_for:
    host: "{{ domain }}"
    port: 80
    timeout: 60
  register: wordpress_up
  failed_when: False

- name: Copia nginx-https.conf para o server
  copy: 
    src: nginx-https.conf 
    dest: "/home/{{ usuario }}/nginx-conf/nginx.conf"
    owner: "{{ usuario }}"
    group: "{{ usuario }}"
    mode: u=rw,g=r,o=r
  notify: restart proxy

- name: Copia options-ssl-nginx.conf para o server
  copy: 
    src: options-ssl-nginx.conf 
    dest: "/home/{{ usuario }}/nginx-conf/"
    owner: "{{ usuario }}"
    group: "{{ usuario }}"
    mode: u=rw,g=r,o=r
  notify: restart proxy

- debug:
    msg: 
      - "Wordpress está no AR!!!"
      - "Disponível em https://{{ domain }}/"
  when: wordpress_up.state is defined and wordpress_up.state == "started"
...