version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/php:8.1.9
        environment:
          WORDPRESS_DB_HOST: localhost
          WORDPRESS_DB_USER: user
          WORDPRESS_DB_PASSWORD: password
          WORDPRESS_DB_NAME: technical_challenge_03_development
      - image: mysql:8.0.30
        environment:
          MYSQL_DATABASE: technical_challenge_03_development
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_RANDOM_ROOT_PASSWORD: true
jobs:
  ci_job:
    working_directory: ~/technical_challenge_03
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Apache2
          command: |
            sudo add-apt-repository ppa:ondrej/php -y
            sudo apt update
            sudo apt install -y apache2 libapache2-mod-php8.1

            sudo rm -rf /var/www/html
            sudo cp -R . /var/www/html
            sudo chown circleci:circleci -R /var/www/html
      - run:
          name: Mysql
          command: |
            sudo apt install -y php8.1-mysql
      - run:
          name: Setup
          command: |
            sudo service apache2 start
            chmod +x devops/**/*.sh
            ./devops/wordpress/setup.sh -t 'My Blog' -u user -p password -e user@email.com
      - run:
          name: WPScan
          command: |
            sudo apt install -y ruby-dev
            sudo gem install wpscan
workflows:
  ci_workflow:
    jobs:
      - ci_job
