---
#site.yml:
- name: Example play
  hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_private_key_file: "../keys/devops-apiki-key"
  tasks:
   
    - name: copy docker-compose config      
      copy:
        src: ../docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml        
        mode: 0644

    - name: copy environment file
      copy:
        src: ../environment.env
        dest: /home/ubuntu/environment.env
        mode: 0644

    - name: create conf directory
      file:
        path: /srv/nginx-proxy/conf
        state: directory
        mode: 0755
    
    - name: copy nginx config
      copy:
        src: conf/site.conf
        dest: /srv/nginx-proxy/conf/site.conf
        mode: 0644

    - name: Run containers  
      shell:
        cmd: "docker-compose up -d"
        chdir: /home/ubuntu