name: Desafio DevOps Apiki

on:
  push:
    branches: [ claudio-estevam ]

jobs:
  Build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@claudio-estevam
      - name: Create .env
        run: echo 'PORT=${{ secrets.PORT }}' > .env
      
      - name: Start running Docker
        run: docker-compose up -d
      - name: Deploy to Server
        uses: ssh-deploy@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}