name: Deploy

on:
  push:
    branches:
    - Marcelo-Michels

jobs:
  deploy:
    name: "Deploy to server"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/server.key
          chmod 600 ~/.ssh/server.key
          cat >>~/.ssh/config <<END
          Host server
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/server.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SERVER_SSH_USER }}
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SSH_HOST: ${{ secrets.SERVER_SSH_HOST }}

      - name: Test
        run: ssh server 'whoiam'

      #- name: Check out the source
      #  run: ssh server 'cd my-application && git fetch && git reset --hard origin/master'

      #- name: Start the server
      #  if: ${{ always() }}
      #  run: ssh server 'sudo systemctl start my-application'
